### ISSUE TITLE
Newtype coersion with newtype > 0.4.4

### ISSUE THREAD

**Issue by benshaw** [gvolpe/pfps-shopping-cart#127]
in newtype 0.4.4 repr becomes a private 

https/repo1.maven.org/maven2/io/estatico/newtype_2.13/0.4.4/newtype_2.13-0.4.4-sources.jar!/io/estatico/newtype/Coercible.scala

```
final class CoercibleIdOps[A](private val repr: A) extends AnyVal {
  @inline def coerce[B](implicit ev: Coercible[A, B]): B = repr.asInstanceOf[B]
}
```
thus 

```
  implicit def coercibleEncoder[A: Coercible[B, *], B: Encoder]: Encoder[A] =
    Encoder[B].contramap(_.repr.asInstanceOf[B])
```

```
pfps-shopping-cart/modules/core/src/main/scala/shop/http/json.scala:46:28: value repr is not a member of type parameter A
[error]     Encoder[B].contramap(_.repr.asInstanceOf[B])
```

**Comment by gvolpe** [comment]
Related: https://github.com/gvolpe/pfps-shopping-cart/pull/109

**Comment by benshaw** [comment]
Im happy to work on this if you have any suggestions but pretty green
my first thought is using _.coerce[B] but that requires an implicit ev: Coercible[A, B] which is not in scope

**Comment by gvolpe** [comment]
Haven't looked into the issue so I don't know what the solution would be either. If you want to give it a spin, go for it :)

**Comment by benshaw** [comment]
Ill see what i can do
Best ive been able to come up with so far is to move away from coercible and specifically have a decoder for each newtype

```
implicit val postgresStatusEncoder: Encoder[PostgresStatus] = (a: PostgresStatus) => a.value.asJson
```

**Comment by gvolpe** [comment]
The idea is to keep it generic :)

**Comment by benshaw** [comment]
I get that but it seems the design of newtype does not make it easy and the developers specifically recommend against it https://github.com/estatico/scala-newtype#coercible-instance-trick

**Comment by gvolpe** [comment]
Right, it's just a trade-off between doing it the "recommended way" and eliminating as much boilerplate as possible. I chose the latter acknowledging this trade-off and I would like to keep it this way for consistency with the book.

**Comment by benshaw** [comment]
I agree i think there should be a newtype-http4s plugin that does this
Ive been playing with it a little but havent gotten far ill see what i can come up with

**Comment by gvolpe** [comment]
FWIW this works:

```scala
 implicit def coercibleEncoder[A: Coercible[B, *], B: Encoder]: Encoder[A] =
    Encoder[B].contramap(_.asInstanceOf[B])
```

After all, `repr` was represents a "safe casting" so we can assume the same given a `Coercible[B, A]` in scope.

**Comment by benshaw** [comment]
from the newtype gitter.im (https://gitter.im/estatico/scala-newtype)

Cary Robbins
@carymrobbins
14:49
Circe's DerivedAsObjectEncoder derivation looks like this

abstract class DerivedAsObjectEncoder[A] extends Encoder.AsObject[A]

object DerivedAsObjectEncoder {
  implicit def deriveEncoder[A, R](implicit
    gen: LabelledGeneric.Aux[A, R],
    encode: Lazy[ReprAsObjectEncoder[R]]
  ): DerivedAsObjectEncoder[A] = new DerivedAsObjectEncoder[A] {
    final def encodeObject(a: A): JsonObject = encode.value.encodeObject(gen.to(a))
  }
}

So one thing that might make stuff like this a little nicer is to provide some sort of generic deriving machinery for newtypes
I can envision some sort of newtype-shapeless library that produces Generic instances for newtypes
Oh I just realized I mixed up your two types. The above may still be a good idea, but not useful for your problem
Cary Robbins
@carymrobbins
14:56

@BenShaw You can derive circe instances like this -

object healthcheck {
  @newtype case class PostgresStatus(value: Boolean)
  object PostgresStatus {
    // The `deriving` name here is magically available here in the
    // companion object thanks to the @newtype macro.
    implicit val circeEncoder: Encoder[PostgresStatus] = deriving
    implicit val circeDecoder: Decoder[PostgresStatus] = deriving
  }
}

You can reduce boilerplate by using scalaz-deriving

object healthcheck {
  @deriving(Encoder, Decoder)
  @newtype case class PostgresStatus(value: Boolean)
}

For details on newtype's built-in deriving mechanism, see https://github.com/estatico/scala-newtype#companion-objects

**Comment by gvolpe** [comment]
Yeah I'm aware of those `deriving` methods. They created the same amount of boilerplate, though.

**Comment by benshaw** [comment]
Agree and they pollute the model

**Comment by benshaw** [comment]
I was wondering if there was a more newtype idiomatic way of achieving the same thing but i dont think there is unfortunately

**Comment by gvolpe** [comment]
The approach using `scalaz-deriving` is quite reasonable (more *a la Haskell*) but unfortunately doesn't support derivation for typeclasses from projects such as `http4s` and `ciris`.

Still, we can take advantage of Scala not being Haskell and do it generally whenever we can, even at the expense of using a safe casting technique.

**Comment by carymrobbins** [comment]
I think `scalaz-deriving` should work for any type class of kind `* -> *` because of the special support for `newtype` it provides. So in these specific cases it _should_ work for http4s and circe instances just fine.

**Comment by benshaw** [comment]
@carymrobbins the issue then is that the model will need to know about serialization (include the Decoder and Encoder) and this goes against my understanding the design (correct me if am wrong @gvolpe) (and the design of Circe https://github.com/hendisantika/circe/blob/master/DESIGN.md)
