### ISSUE TITLE
Design Diagram or Flow Diagram

### ISSUE THREAD

**Issue by imranbutt-java** [gvolpe/pfps-shopping-cart#234]
I won't say it is an issue but for the sake of request, I opened an issue. May we get any Design Diagram (UML) or Flow Diagram, that picture the whole application flow.
(Beside that, I am following the book with the code, that is super awesome, thanks for such a great content.)

**Comment by gvolpe** [comment]
I added a components overview section to the README file (represents the 2nd edition version), that shows the different layers from the entry point (Main and Modules) to the HTTP layer, services, storage (PostgreSQL and Redis) and custom effects. It's not a flow diagram but should be enough, the application is really that simple :)
