### ISSUE TITLE
Can't run shopping app

### ISSUE THREAD

**Issue by sb-snrg** [gvolpe/pfps-shopping-cart#464]
Hi Gabriel Volpe

First of all, thanks for your excellent book.
I can't run the shopping app. i'm on mac and I use docker for mac. Need your help, I'm newbie.

`Removing app_shopping_cart_1
Recreating a5556a84df46_app_shopping_cart_1 ... error

ERROR: for a5556a84df46_app_shopping_cart_1  Cannot start service shopping_cart: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/opt/docker/bin/shopping-cart-core": stat /opt/docker/bin/shopping-cart-core: no such file or directory: unknown

ERROR: for shopping_cart  Cannot start service shopping_cart: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/opt/docker/bin/shopping-cart-core": stat /opt/docker/bin/shopping-cart-core: no such file or directory: unknown
ERROR: Encountered errors while bringing up the project.`

**Comment by gvolpe** [comment]
See https://github.com/gvolpe/pfps-shopping-cart/issues/448, and for questions, please prefer the [Gitter channel](https://gitter.im/pfp-scala/community).
